<?php

use COMMON__\svc\Misc;
?>
<!doctype html>
<html lang="fr">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">
	<!--	<link rel="icon" href="favicon.ico"> -->
	<link rel="icon" href="data:;base64,iVBORw0KGgo=">

	<title><?= $page["title"] ?></title>

	<link href="<?= $BASE ?>/vendor/twbs/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
	<link href="<?= $BASE ?>/vendor/components/jqueryui/themes/base/jquery-ui.min.css" rel="stylesheet">

	<!--  font awesome -->
	<link href="<?= $BASE ?>/vendor/fortawesome/font-awesome/css/fontawesome.css" rel="stylesheet">
	<link href="<?= $BASE ?>/vendor/fortawesome/font-awesome/css/brands.css" rel="stylesheet">
	<link href="<?= $BASE ?>/vendor/fortawesome/font-awesome/css/solid.css" rel="stylesheet">

	<link href="<?= $BASE ?>/vendor/select2/select2/dist/css/select2.min.css" rel="stylesheet" />

	<!-- Custom styles for this template -->
	<?php
	// import assets from previous directories
	$path = $page["name"];
	$paths = [];
	while ($path !== ".") {
		array_unshift($paths, $path);
		$path = dirname($path);
	}

	Misc::load_asset("COMMON__", "index", "css");
	foreach ($paths as $path) {
		Misc::load_asset($page["module"], $page["name"], "css");
		Misc::load_asset($page["module"], $page["name"] . "/index", "css");
	}

	$css = array_unique($f3->get("page.css"));
	foreach ($css as $file) {
	?>
		<link href="<?= $file ?>" rel="stylesheet">
	<?php
	}
	?>

	<link rel="icon" href="data:;base64,iVBORw0KGgo=">
</head>

<body>

	<!--- YOUR CODE HERE -->
	
	<!--- END OF YOUR CODE -->
	
	<!-- static JS -->
	<script src="<?= $BASE ?>/vendor/components/jquery/jquery.min.js"></script>
	<script src="<?= $BASE ?>/vendor/twbs/bootstrap/dist/js/bootstrap.min.js"></script>
	<script src="<?= $BASE ?>/vendor/components/jqueryui/jquery-ui.min.js"></script>
	<!--	 <script src="../../assets/js/vendor/popper.min.js"></script> -->

	<script src="<?= $BASE ?>/vendor/select2/select2/dist/js/select2.min.js"></script>
	<script src="<?= $BASE ?>/vendor/select2/select2/dist/js/i18n/fr.js"></script>

	<?php
	Misc::load_asset("COMMON__", "index", "js");
	foreach ($paths as $path) {
		Misc::load_asset($page["module"], $page["name"], "js");
		Misc::load_asset($page["module"], $page["name"] . "/index", "js");
	}
	?>

	<!-- auto JS from path + explicit JS from controler -->
	<?php
	$js = $f3->get("page.js");
	if (!empty($js)) {
		$js = array_unique($js);
		foreach ($js as $file) {
	?>
			<script src="<?= $file ?>"></script>
	<?php
		}
	}
	?>
</body>

</html>