[globals]
; uncomment only for dev
;DEBUG = 3

[database]
type = mysql
host = localhost
port = 3306
name = 
user = 
password = 

[conf]
;APP_NAME_suffix = ENV
COMPANY_NAME = company_name
COMPANY_LOGO = company.png

[binance]
start_date = 2025-10-01
env = prod

[binance.envs.prod]
key = private_key
secret = private_secret

[binance.envs.demo]
key = private_key
secret = private_secret

[binance.envs.test]
key = private_key
secret = private_secret

[auth]
login = admin
password_bcrypt = $1$mw3pLQ9t$iCdUi4M/ciFNxhSbd2wVs1
# generate with : "openssl passwd"
