		<h1><?= $page["title"] ?></h1>

		<div class="d-flex">
			<div id="chartContainer" class="flex-grow-1">
				<canvas id="chart"></canvas>
				<canvas id="overlay"></canvas>
			</div>
			<div class="">
				<div id="stats">
					<h5>Stats</h5>
					<div class="text-nowrap"><span id="stats-mode">viewport</span> : <span id="stats-points">–</span> points</div>
					<div class="text-nowrap">start : <span id="stats-start">–</span></div>
					<div class="text-nowrap">end : <span id="stats-end">–</span> (<span id="stats-pct">–</span> %)</div>
					<div class="text-nowrap">low : <span id="stats-min">–</span></div>
					<div class="text-nowrap">high : <span id="stats-max">–</span> (<span id="stats-amp-pct">–</span> %)</div>
				</div>
			</div>
		</div>
		
		<script>
			// données
			var data = <?= json_encode($data) ?>;
			data.forEach(element => {
				element.x = new Date(element.x); // convert php date string to js date
			});
			// console.log(data);
			
			// Points clés
			keyPoints = [];
			<?php
			if (!empty($first)) {
				?>
				first = <?= json_encode($first) ?>;
				first.x = new Date(first.x); // convert php date string to js date
				first.label = "start";
				keyPoints.push(first);
				<?php
			}
			if (!empty($last)) {
				?>
				last = <?= json_encode($last) ?>;
				last.x = new Date(last.x); // convert php date string to js date
				last.label = "end";
				keyPoints.push(last);
				<?php
			}
			?>
			// console.log(keyPoints);
		</script>
		
		<script src="<?= $BASE . "/node_modules/chart.js/dist/chart.umd.js" ?>"></script>
		<script src="<?= $BASE . "/node_modules/chartjs-adapter-date-fns/dist/chartjs-adapter-date-fns.bundle.min.js" ?>"></script>
		<script src="<?= $BASE . "/node_modules/chartjs-plugin-zoom/dist/chartjs-plugin-zoom.min.js" ?>"></script>