		<h1><?= $page["title"] ?></h1>
		
		<h2 class="mt-2"><a href="<?= $BASE . $f3->alias("download") ?>">
			<i class="fa-solid fa-cloud-arrow-down"></i> download data from binance
		</a></h2>
		<h2 class="mt-2"><a href="<?= $BASE . $f3->alias("import") ?>">
			<i class="fa-solid fa-file-import"></i> import into db
		</a></h2>
		<h2 class="mt-2"><a href="<?= $BASE . $f3->alias("simulate") ?>">
			<i class="fa-solid fa-file-contract"></i> simulate
		</a></h2>
	</main>