<?php

use COMMON__\svc\Stuff;

?>
		
		<h1><?= $page["title"] ?></h1>

		<div class="row">
			<div class="col">
				
				<h3 class="mt-2">
					<a href="<?= $BASE . $f3->alias("watchdog" . ($global_watchdog->isRunning() ? "Kill" : "Run")) ?> ">
						global
					</a>
					<div class="form-check form-switch d-inline-block">
						<input class="form-check-input" type="checkbox" role="switch" id="global_watchdog" disabled <?= $global_watchdog->isRunning() ? "checked" : "" ?>>
						<label class="form-check-label" for="global_watchdog"></label>
					</div>
					<?php
					$last_update_dt = $global_watchdog->getLastUpdate(); /** @var DateTimeInterface $last_update_dt */
					if (!empty ($last_update_dt)) {
						$diff = $last_update_dt->diff(new dateTime);
						?>
						<?= $last_update_dt->format(Stuff::datetime_french_format) ?>
						(
						<?= $diff->y ? $diff->y."y" : "" ?> <?= $diff->m ? $diff->m."m" : "" ?> <?= $diff->d ? $diff->d."d" : "" ?> 
						<?= $diff->h ? $diff->h."h" : "" ?> <?= $diff->i ? $diff->i."m" : "" ?> <?= $diff->s ? $diff->s."s" : "" ?>
						 ago )
						<?php
					}
					?>
				</h3>
				
			</div>
		</div>

		</main>