<?php
use COMMON__\svc\Binance;
use COMMON__\svc\Stuff;

?>
		<h1><?= $page["title"] ?></h1>

		<table class="table table-bordered">
			<thead>
				<tr>
					<th rowspan=2 class="text-end">
						asset <br>
						<span class="text-secondary fw-normal">name</span>
					</th>
					<th rowspan=2 class="text-center align-middle">accounting</th>
					<th rowspan=2 class="text-center align-middle">balance</th>
					<th rowspan=2 class="text-center align-middle">price</th>
					<th colspan=2 class="text-center align-middle">trades</th>
					<th colspan=2 class="text-center">orders</th>
				</tr>
				<tr>
					<th class="text-center align-middle">cost</th>
					<th class="text-center align-middle">margin</th>
					<th class="text-center align-middle">Take Profit</th>
					<th class="text-center align-middle">Stop Loss</th>
				</tr>
			</thead>
			<tbody>
				<?php
				$accounting_total = 0;
				foreach ($accounting->get_accounts_assets() as $asset) {
					$account = $accounting->get_account($asset);
					?>
					<tr>
						<td class="text-end">
							<?= $account->get_asset() ?> <br/>
							<span class="text-secondary"><?= $capital_configs [$asset] ["name"] ?? "" ?></span>
						</td>
						
						<td class="text-start">
							<?= Stuff::format_crypto ($account->get_quantity()) ?> <br/>
						<?php
						if(!empty($assets_reference_price [$asset])) {
							$account_reference_qty = $account->get_quantity() * $assets_reference_price [$asset];
							$accounting_total += $account_reference_qty;
							?>
							<span class="text-secondary"><?= Stuff::format_fiat ( $account_reference_qty ) ?> <?= Binance::reference_asset ?></span>
							<?php
						}
						?>
						</td>

						<?php
						if (!empty($balances [$asset])) {
							?>
							<td class="text-start">
								<?= Stuff::format_crypto ($balances [$asset]) ?> <br/>
								<span class="text-secondary"><?= Stuff::format_fiat ($balance_reference_qty [$asset]) ?> <?= Binance::reference_asset ?></span>
							</td>
							<?php
						}
						else {
							?>
							<td>&nbsp;</td>
							<?php
						}
						?>

						<?php
						if (!empty($assets_reference_price [$asset])) {
							?>
							<td class="text-start">
								1 = <br/>
								<?= Stuff::format_crypto ($assets_reference_price [$asset]) ?>
							</td>
							<?php
						}
						else {
							?>
							<td>&nbsp;</td>
							<?php
						}
						?>
						
						<td class="">
							<?= "" ?>
						</td>

						<td class="">
							<?= "" ?>
						</td>

						<td class="">
							<?= "" ?>
						</td>
					</tr>
				<?php
				}
				?>
			</tbody>
			<tfoot>
				<tr>
					<th class="text-end">
						<?= Binance::reference_asset ?>
					</th>
					<th class="text-start">
						<?= stuff::format_fiat ($accounting_total) ?>
					</th>
					<th class="">
						<?= stuff::format_fiat (array_sum ($balance_reference_qty)) ?>
					</th>
					<th colspan=5 class="text-start">
						&nbsp;
					</th>
				</tr>
			</tfoot>
		</table>
		
		</main>