		<h1><?= $page["title"] ?></h1>

		<table class="table table-bordered">
			<thead>
				<tr>
					<th colspan=2 class="text-center align-middle">balance</th>
					<th colspan=2 class="text-center align-middle">accounting</th>
					
					
					<th rowspan=2 class="text-center align-middle">price</th>
					<th rowspan=2 class="text-center align-middle">margin</th>
					<th colspan=2 class="text-center">orders</th>
				</tr>
				<tr>
					<th class="text-end">quantity</th>
					<th class="text-start">asset</th>
					<th class="text-end">quantity</th>
					<th class="text-start">asset</th>
					<th class="text-center">Take Profit</th>
					<th class="text-center">Stop Loss</th>
				</tr>
			</thead>
			<tbody>
				<?php
				foreach ($accounting->get_accounts_assets() as $asset) {
					$account = $accounting->get_account($asset);
					?>
					<tr>
						<?php
						if (!empty($balances [$asset])) {
							?>
							<td class="text-end">
								<?= $balances [$asset] ?> <br/>
								<span class="text-secondary"><?= "xxx" ?></span>
							</td>
							<td class="">
								<?= $asset ?> <br/>
								<span class="text-secondary"><?= "EUR" ?></span>
							</td>
							<?php
						}
						else {
							?>
							<td colspan=2>&nbsp;</td>
							<?php
						}
						?>
						<td class="text-end">
							<?= $account->get_quantity() ?>
						</td>
						<td class="">
							<?= $account->get_asset() ?>
						</td>
						<td class="">
							<?= "" ?>
						</td>
						<td class="">
							<?= "" ?>
						</td>
						<td class="">
							<?= "" ?>
						</td>
						<td class="">
							<?= "" ?>
						</td>
					</tr>
				<?php
				}
				?>
			</tbody>
			<tfoot>
				<!-- <tr>
					<th></th>
				</tr> -->
			</tfoot>
		</table>
		
		</main>