<?php
use COMMON__\svc\Binance;
use COMMON__\svc\Stuff;

?>
		<h1><?= $page["title"] ?></h1>

		<table class="table table-bordered">
			<thead>
				<tr>
					<th colspan=3 class="text-center align-middle">balance</th>
					<th colspan=2 class="text-center align-middle">accounting</th>
					<th colspan=2 class="text-center align-middle">trades</th>
					<th colspan=2 class="text-center">orders</th>
				</tr>
				<tr>
					<th class="text-end">asset</th>
					<th class="text-start">quantity</th>
					<th class="text-center">price</th>
					<th class="text-end">quantity</th>
					<th class="text-start">asset</th>
					<th class="text-center">cost</th>
					<th class="text-center">margin</th>
					<th class="text-center">Take Profit</th>
					<th class="text-center">Stop Loss</th>
				</tr>
			</thead>
			<tbody>
				<?php
				foreach ($accounting->get_accounts_assets() as $asset) {
					$account = $accounting->get_account($asset);
					?>
					<tr>
						<?php
						if (!empty($balances [$asset])) {
							?>
							<td class="text-end">
								<?= $asset ?> <br/>
								<span class="text-secondary"><?= Binance::reference_asset ?></span>
							</td>
							<td class="text-start">
								<?= Stuff::format_crypto ($balances [$asset]) ?> <br/>
								<span class="text-secondary"><?= Stuff::format_fiat ($balance_reference_prices [$asset]) ?></span>
							</td>
							<td class="text-center">
								1 = <br/>
								<?= Stuff::format_crypto ($assets_reference_price [$asset]) ?>
							</td>
							<?php
						}
						else {
							?>
							<td colspan=3>&nbsp;</td>
							<?php
						}
						?>
						<td class="text-end">
							<?= Stuff::format_crypto ($account->get_quantity()) ?>
						</td>
						<td class="">
							<?= $account->get_asset() ?>
						</td>
						<td class="">
							<?= "" ?>
						</td>
						<td class="">
							<?= "" ?>
						</td>
						<td class="">
							<?= "" ?>
						</td>
					</tr>
				<?php
				}
				?>
			</tbody>
			<tfoot>
				<tr>
					<th colspan=2 class="text-center">
						TOTAL
					</th>
				</tr>
				<tr>
					<th class="text-end">
						<?= stuff::format_fiat (array_sum ($balance_reference_prices)) ?>
					</th>
					<th class="">
						<?= Binance::reference_asset ?>
					</th>
				</tr>
			</tfoot>
		</table>
		
		</main>