		<?php

		use COMMON__\svc\Binance;
		use COMMON__\svc\Stuff;
		?>

		<h1><?= $page["title"] ?></h1>

		<table class="table table-bordered">
			<thead>
				<tr>
					<th>OrderListId</th>
					<th>OrderId</th> <!-- group by -->
					<th>Time</th>
					<th>Price</th>
					<th>Qty</th>
					<th>Commission</th>
					<th>IsBuyer</th>
					<th>IsMaker</th>
					<th>IsBestMatch</th>
				</tr>
			</thead>
			<tbody>
				<?php
				foreach ($data as $orderListId => $orderListGroup) {
				?>
					<tr>
						<td class="align-middle" rowspan="<?= count($orderListGroup) ?>"><?= $orderListId ?></td>
						<?php
						$firstOrder = true;
						foreach ($orderListGroup as $row) {
							if (!$firstOrder) {
							?>
					<tr>
							<?php
							}
							?>
						<td><?= $row["OrderId"] ?></td>
						<td><?= Binance::timestamp_to_datetime($row["Time"])->format(Stuff::datetime_french_format . ".u") ?></td>
						<td> 1 ETH = <?= $row["Price"] ?> €</td>
						<td><?= $row["Qty"] ?> ETH (<?= $row["QuoteQty"] ?> €)</td>
						<td><?= $row["Commission"] ?> <?= $row["CommissionAsset"] ?></td>
						<td><?= $row["IsBuyer"] ?></td>
						<td><?= $row["IsMaker"] ?></td>
						<td><?= $row["IsBestMatch"] ?></td>
						<?php
						$firstOrder = false;
					}
					?>
					</tr>
				<?php
				}
				?>
			</tbody>
			<tfoot>
				<!-- <tr>
					<th></th>
				</tr> -->
			</tfoot>
		</table>

		</main>