		<?php

		use COMMON__\svc\Binance;
		use COMMON__\svc\Stuff;
		?>

		<h1><?= $page["title"] ?></h1>

		<table class="table table-bordered">
			<thead>
				<tr>
					<th>orderListId</th>
					<th>orderId</th> <!-- group by -->
					<th>time</th>
					<th>price</th>
					<th>qty</th>
					<th>commission</th>
					<th>isBuyer</th>
					<th>isMaker</th>
					<th>isBestMatch</th>
				</tr>
			</thead>
			<tbody>
				<?php
				foreach ($data as $orderListId => $orderListGroup) {
				?>
					<tr>
						<td class="align-middle" rowspan="<?= count($orderListGroup) ?>"><?= $orderListId ?></td>
						<?php
						$firstOrder = true;
						foreach ($orderListGroup as $row) {
							if (!$firstOrder) {
							?>
					<tr>
							<?php
							}
							?>
						<td><?= $row["orderId"] ?></td>
						<td><?= Binance::timestamp_to_datetime($row["time"])->format(Stuff::datetime_french_format . ".u") ?></td>
						<td> 1 ETH = <?= $row["price"] ?> €</td>
						<td><?= $row["qty"] ?> ETH (<?= $row["quoteQty"] ?> €)</td>
						<td><?= $row["commission"] ?> <?= $row["commissionAsset"] ?></td>
						<td><?= $row["isBuyer"] ?></td>
						<td><?= $row["isMaker"] ?></td>
						<td><?= $row["isBestMatch"] ?></td>
						<?php
						$firstOrder = false;
					}
					?>
					</tr>
				<?php
				}
				?>
			</tbody>
			<tfoot>
				<!-- <tr>
					<th></th>
				</tr> -->
			</tfoot>
		</table>

		</main>