		<h1><?= $page["title"] ?></h1>

		<?php
		$headers = array_keys($data[0]);
		?>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>OrderListId</th> <!-- group by -->
					<th>OrderId</th> <!-- group by -->
					<th>Time</th>
					<th>Price</th>
					<th>Qty</th>
					<th>Commission</th>
					<th>IsBuyer</th>
					<th>IsMaker</th>
					<th>IsBestMatch</th>
				</tr>
			</thead>
			<tbody>
				<?php
				foreach ($data as $row) {
				?>
					<tr>
						<td><?= $row["OrderListId"] ?></td>
						<td><?= $row["OrderId"] ?></td>
						<td><?= $row["Time"] ?></td>
						<td> 1 ETH = <?= $row["Price"] ?> €</td>
						<td><?= $row["Qty"] ?> ETH (<?= $row["QuoteQty"] ?> €)</td>
						<td><?= $row["Commission"] ?> <?= $row["CommissionAsset"] ?></td>
						<td><?= $row["IsBuyer"] ?></td>
						<td><?= $row["IsMaker"] ?></td>
						<td><?= $row["IsBestMatch"] ?></td>
					</tr>
				<?php
				}
				?>
			</tbody>
			<tfoot>
				<!-- <tr>
					<th></th>
				</tr> -->
			</tfoot>
		</table>

		</main>